# -*- coding: utf-8 -*-
"""icnumbergender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12iVsOxSKv6fKr1mw7mNYd61tYwnQt3wy
"""

# import library
from google.colab import files
import pandas as pd
import numpy as np
import datetime

# upload files
upload_file = files.upload()
file = next(iter(upload_file))
df = pd.read_excel(file)

# label gender by national id
def gender_by_national_id(df):
  filtered_df = df[
      (df['National ID'].astype(str).str.len() == 14) &
      df['National ID'].notna() &
      (df['National ID'] != '')
      ]

  filtered_df['Gender'] = np.where(
      filtered_df['National ID'].astype(str).str[-1].astype(int) % 2 == 0,
      'Female',
      'Male'
      )

  df.update(filtered_df['Gender'])


  return df

df = gender_by_national_id(df)

# rename file with new name
current_filename = file[:-5]
output_file = f'Updated {current_filename}.xlsx'

# save to excel and download
df.to_excel(output_file, index = False)
files.download(output_file)

